package com.samiagrihub.common.audit;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    USER_REGISTERED,
    OTP_VERIFIED,
    COURSE_PUBLISHED,
    COURSE_ARCHIVED,
    ADVISORY_PUBLISHED,
    ADVISORY_ARCHIVED,
    BUSINESS_VERIFICATION_CHANGED,
    PRODUCE_LISTING_MODERATED,
    DEMAND_LISTING_MODERATED,
    OPPORTUNITY_MODERATED
}
